name: Deploy To S3 And Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        # 라이브러리 actions/checkout@v4를 사용하여 GitHub 저장소의 파일을 불러옵니다.
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm install

      - name: 빌드하기
        run: npm run build

      - name: debugging
        run: |
          ls
          cd dist
          ls