name: Deploy To S3 And Invalidate CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        # 라이브러리 actions/checkout@v4를 사용하여 GitHub 저장소의 파일을 불러옵니다.
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm install

      - name: 빌드하기
        run: npm run build

      - name: debugging
        run: |
          ls
          echo "--------"
          cd dist
          ls

      # AWS 리소스에 접근하기 위해 AWS 자격 증명을 설정
      - name: AWS Resource에 접근할 수 있게 AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일들 전체 삭제
        # --recursive 옵션을 사용하여 S3 버킷에 있는 모든 파일을 재귀적으로 삭제
        run: |
          aws s3 rm --recursive s3://facebook-web-page3

      - name: S3에 빌드된 파일 업로드
        run: aws s3 cp ./dist s3://facebook-web-page3/ --recursive 