# Workflow
name: Github Actions 실행시켜보기

# 이 워크플로우는 main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches:
      - main

# Workflow는 여러개의 jobs로 이루어질 수 있음
jobs:
  My-deploy-job:
    # ubuntu-latest: 최신 우분투 버전에서 실행
    runs-on: ubuntu-latest

    # jobs 안에 steps가 들어감
    steps:
      - name: Hello World
        run: echo "Hello, World!"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"
          pwd 
          
      - name: Github Actions 자체 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA

      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secrets.MY_SECRET }}
          echo ${{ secrets.MY_HOBBY }}

